### PR TITLE
Updated .gitignore

### PR DESCRIPTION
**Pull request by jflip**
Getting setup with the project, building added loads of changes. Figured this was a quick change to make but wanted to check with yourself first 👍

### CODE REVIEW

**Comment by Floppy** [comment]
Ah, yes! I recently switched from having that in the repo to using actions to build and release it, but forgot to add to gitignore. Thanks!

**Comment by Floppy** [comment]
Sorry I've not added a decent README yet btw, it's an open issue (#20)!

**Comment by jflip** [comment]
Hey no worries I know it's an early project and I'm pretty new to open source so happy to learn more about the project as I dig around in the code and hopefully submit a useful pull request or two 🙂

**Comment by Floppy** [comment]
The main think you want at this stage is probably `yarn start` to get the local server up and running. All PRs welcome, it's great to have someone else looking at it 👍

**Pull request merged**
